name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ["release"]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: package.json
          cache: npm

      - run: npm ci
      - run: npm run lint-fix || true
      - run: npm run style-fix || true

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
